import {
  KnowledgeGraphEntityNode,
  KnowledgeGraphRelationEdge,
  StockKnowledgeGraphItem,
} from "../types/stockTypes";

export interface StockEcosystemDefinition {
  symbol: string;
  companyName: string;
  sector: string;
  marketCap: string;
  beta: number;
  rootDescription: string;
  nodes: KnowledgeGraphEntityNode[];
  edges: KnowledgeGraphRelationEdge[];
}

/**
 * 真实美股核心标的产业链拓扑知识库 (涵盖半导体、云巨头、算力硬件、车企、金融与生物科技)
 */
export const REAL_STOCK_ECOSYSTEM_REGISTRY: Record<string, StockEcosystemDefinition> = {
  NVDA: {
    symbol: "NVDA",
    companyName: "NVIDIA Corporation (英伟达)",
    sector: "半导体与 AI 算力芯片",
    marketCap: "$3.2T",
    beta: 1.65,
    rootDescription: "全球 GPU 算力龙头与 CUDA AI 软件生态核心中枢",
    nodes: [
      {
        id: "NVDA",
        name: "英伟达 (NVDA)",
        type: "ROOT_STOCK",
        marketSymbol: "NVDA",
        sector: "半导体设计",
        beta: 1.65,
        marketCap: "$3.2T",
        recentSignalScore: 0.85,
        description: "Blackwell / Hopper GPU 架构算力卡与 CUDA 开发者生态垄断",
        recencyWeight: 1.0,
      },
      {
        id: "TSM",
        name: "台积电 (TSMC)",
        type: "SUPPLIER",
        marketSymbol: "TSM",
        sector: "晶圆代工",
        beta: 1.2,
        marketCap: "$880B",
        recentSignalScore: 0.75,
        description: "3nm/4nm 先进制程与 CoWoS 先进封装唯一核心代工厂 (产能敞口 85%+)",
        recencyWeight: 1.0,
      },
      {
        id: "ASML",
        name: "阿斯麦 (ASML)",
        type: "SUPPLIER",
        marketSymbol: "ASML",
        sector: "半导体设备",
        beta: 1.3,
        marketCap: "$350B",
        recentSignalScore: 0.5,
        description: "High-NA EUV 光刻机独家垄断供应商，制约上游晶圆扩产节奏",
        recencyWeight: 1.0,
      },
      {
        id: "MSFT",
        name: "微软 Azure (MSFT)",
        type: "CLIENT",
        marketSymbol: "MSFT",
        sector: "云计算与软件",
        beta: 1.15,
        marketCap: "$3.1T",
        recentSignalScore: 0.8,
        description: "NVDA 全球最大客户之一 (占其总算力采购 15%-19%)，OpenAI 算力底层支持者",
        recencyWeight: 1.0,
      },
      {
        id: "META",
        name: "Meta Platforms (META)",
        type: "CLIENT",
        marketSymbol: "META",
        sector: "社交网络与 AI",
        beta: 1.35,
        marketCap: "$1.4T",
        recentSignalScore: 0.7,
        description: "Llama 系列开源大模型训练集群主力采购方 (年采购数十万张 H100/H200)",
        recencyWeight: 1.0,
      },
      {
        id: "AMD",
        name: "超威半导体 (AMD)",
        type: "COMPETITOR",
        marketSymbol: "AMD",
        sector: "半导体设计",
        beta: 1.55,
        marketCap: "$240B",
        recentSignalScore: 0.2,
        description: "MI300X/MI350 GPU 同业直接竞品，通过性价比与 ROCm 软件争夺份额",
        recencyWeight: 1.0,
      },
      {
        id: "FED_RATE",
        name: "美联储降息与流动性预期",
        type: "MACRO",
        sector: "宏观流动性",
        beta: 0.9,
        recentSignalScore: 0.4,
        description: "高估值高成长科技股对 10 年期美债收益率及贴现率高度敏感",
        recencyWeight: 1.0,
      },
      {
        id: "AI_CAPEX_THEME",
        name: "北美四大云厂商 AI 资本开支",
        type: "CONCEPT",
        sector: "行业主题与驱动力",
        beta: 1.4,
        recentSignalScore: 0.9,
        description: "MSFT / GOOGL / AMZN / META 年化千亿美元级 AI Capex 增长曲线",
        recencyWeight: 1.0,
      },
    ],
    edges: [
      {
        source: "TSM",
        target: "NVDA",
        relation: "CoWoS 先进封装产能直接决定 Blackwell 出货放量速度",
        relationType: "UPSTREAM_SUPPLIER",
        exposurePct: 0.85,
        elasticity: 0.92,
        timeLagDays: 7,
        impact: "POSITIVE",
        recencyWeight: 1.0,
      },
      {
        source: "ASML",
        target: "TSM",
        relation: "EUV 交付节奏决定台积电扩产周期",
        relationType: "UPSTREAM_SUPPLIER",
        exposurePct: 0.45,
        elasticity: 0.65,
        timeLagDays: 15,
        impact: "POSITIVE",
        recencyWeight: 1.0,
      },
      {
        source: "MSFT",
        target: "NVDA",
        relation: "Azure 云资本开支直接贡献季度数据中心核心营收",
        relationType: "DOWNSTREAM_CLIENT",
        exposurePct: 0.18,
        elasticity: 0.88,
        timeLagDays: 5,
        impact: "POSITIVE",
        recencyWeight: 1.0,
      },
      {
        source: "META",
        target: "NVDA",
        relation: "Llama 训练集群大规模采购算力卡与 InfiniBand 网络套件",
        relationType: "DOWNSTREAM_CLIENT",
        exposurePct: 0.14,
        elasticity: 0.8,
        timeLagDays: 5,
        impact: "POSITIVE",
        recencyWeight: 1.0,
      },
      {
        source: "AMD",
        target: "NVDA",
        relation: "MI300 降价与生态渗透对英伟达中低阶定价权构成轻微挤压",
        relationType: "COMPETITOR",
        exposurePct: 0.12,
        elasticity: -0.4,
        timeLagDays: 3,
        impact: "NEGATIVE",
        recencyWeight: 1.0,
      },
      {
        source: "AI_CAPEX_THEME",
        target: "NVDA",
        relation: "云巨头算力军备竞赛放大 PE 估值中枢与订单能见度",
        relationType: "CONCEPT_THEME",
        exposurePct: 0.75,
        elasticity: 1.25,
        timeLagDays: 2,
        impact: "POSITIVE",
        recencyWeight: 1.0,
      },
      {
        source: "FED_RATE",
        target: "NVDA",
        relation: "利率宽松预期推动成长股估值扩张与大盘流动性溢价",
        relationType: "MACRO_DRIVER",
        exposurePct: 0.35,
        elasticity: 0.7,
        timeLagDays: 1,
        impact: "POSITIVE",
        recencyWeight: 1.0,
      },
    ],
  },

  TSLA: {
    symbol: "TSLA",
    companyName: "Tesla, Inc. (特斯拉)",
    sector: "新能源车、FSD 自动驾驶与人形机器人",
    marketCap: "$750B",
    beta: 2.1,
    rootDescription: "全球智能电动汽车与 FSD 具身智能算力先锋",
    nodes: [
      {
        id: "TSLA",
        name: "特斯拉 (TSLA)",
        type: "ROOT_STOCK",
        marketSymbol: "TSLA",
        sector: "新能源与机器人",
        beta: 2.1,
        marketCap: "$750B",
        recentSignalScore: 0.65,
        description: "全球主力交付 Model 3/Y，FSD V12 端到端模型与 Optimus 机器人量产在即",
        recencyWeight: 1.0,
      },
      {
        id: "CATL",
        name: "宁德时代 / LG 新能源",
        type: "SUPPLIER",
        marketSymbol: "CATL",
        sector: "动力电池",
        beta: 1.1,
        recentSignalScore: 0.4,
        description: "磷酸铁锂与三元锂电芯核心供应商，碳酸锂价格直接影响整车毛利率",
        recencyWeight: 1.0,
      },
      {
        id: "NVDA_DOJO",
        name: "英伟达 GPU / 自研 Dojo 算力集群",
        type: "SUPPLIER",
        marketSymbol: "NVDA",
        sector: "AI 算力基建",
        beta: 1.6,
        recentSignalScore: 0.85,
        description: "FSD 视频端到端训练需数万张 H100 集群算力支持",
        recencyWeight: 1.0,
      },
      {
        id: "BYD",
        name: "比亚迪股份 (BYD)",
        type: "COMPETITOR",
        marketSymbol: "BYDDF",
        sector: "新能源汽车",
        beta: 1.3,
        recentSignalScore: 0.6,
        description: "全球销量规模同业竞品，在中低端全球化市场构成剧烈价格战竞争",
        recencyWeight: 1.0,
      },
      {
        id: "RIVN",
        name: "Rivian / 传统美欧主机厂 (Ford/GM)",
        type: "COMPETITOR",
        marketSymbol: "RIVN",
        sector: "电动皮卡与车企",
        beta: 1.8,
        recentSignalScore: -0.2,
        description: "北美电动皮卡与主流乘用车存量市场博弈者",
        recencyWeight: 1.0,
      },
      {
        id: "FSD_ROBOTAXI",
        name: "Robotaxi 无人出行运营概念",
        type: "CONCEPT",
        sector: "商业模式创新",
        beta: 1.7,
        recentSignalScore: 0.7,
        description: "从重资产造车切换为高毛利 SaaS/出行平台分成估值逻辑",
        recencyWeight: 1.0,
      },
      {
        id: "US_AUTO_INTEREST",
        name: "北美汽车消费信贷利率与补贴政策",
        type: "MACRO",
        sector: "宏观消费金融",
        beta: 1.2,
        recentSignalScore: -0.3,
        description: "高息环境抑制消费者月供购车意愿，直接左右交付增速",
        recencyWeight: 1.0,
      },
    ],
    edges: [
      {
        source: "CATL",
        target: "TSLA",
        relation: "电池原材料价格波动对单车毛利率 (Gross Margin) 产生杠杆影响",
        relationType: "UPSTREAM_SUPPLIER",
        exposurePct: 0.4,
        elasticity: 0.6,
        timeLagDays: 10,
        impact: "POSITIVE",
        recencyWeight: 1.0,
      },
      {
        source: "BYD",
        target: "TSLA",
        relation: "海外与中国市场降价促销挤压特斯拉单车净利润中枢",
        relationType: "COMPETITOR",
        exposurePct: 0.3,
        elasticity: -0.55,
        timeLagDays: 3,
        impact: "NEGATIVE",
        recencyWeight: 1.0,
      },
      {
        source: "FSD_ROBOTAXI",
        target: "TSLA",
        relation: "无人出租车牌照与商用里程碑引爆非线性软件估值溢价",
        relationType: "CONCEPT_THEME",
        exposurePct: 0.65,
        elasticity: 1.4,
        timeLagDays: 2,
        impact: "POSITIVE",
        recencyWeight: 1.0,
      },
      {
        source: "US_AUTO_INTEREST",
        target: "TSLA",
        relation: "借贷利率走高导致购车门槛提高，倒逼官方贴息让利",
        relationType: "MACRO_DRIVER",
        exposurePct: 0.5,
        elasticity: -0.75,
        timeLagDays: 5,
        impact: "NEGATIVE",
        recencyWeight: 1.0,
      },
    ],
  },

  AAPL: {
    symbol: "AAPL",
    companyName: "Apple Inc. (苹果公司)",
    sector: "消费电子、端侧 AI 与服务生态",
    marketCap: "$3.4T",
    beta: 1.05,
    rootDescription: "全球消费电子之王，iOS 高黏性软硬件闭环生态",
    nodes: [
      {
        id: "AAPL",
        name: "苹果 (AAPL)",
        type: "ROOT_STOCK",
        marketSymbol: "AAPL",
        sector: "消费电子",
        beta: 1.05,
        marketCap: "$3.4T",
        recentSignalScore: 0.7,
        description: "iPhone 换机周期叠加 Apple Intelligence 端侧 AI 赋能",
        recencyWeight: 1.0,
      },
      {
        id: "TSM",
        name: "台积电 (TSMC)",
        type: "SUPPLIER",
        marketSymbol: "TSM",
        sector: "晶圆代工",
        beta: 1.2,
        marketCap: "$880B",
        recentSignalScore: 0.75,
        description: "A 系列与 M 系列处理器 3nm 先进制程包揽代工",
        recencyWeight: 1.0,
      },
      {
        id: "FOXCONN",
        name: "鸿海富士康 (Foxconn)",
        type: "SUPPLIER",
        marketSymbol: "2317.TW",
        sector: "整机组装",
        beta: 0.95,
        recentSignalScore: 0.3,
        description: "iPhone/MacBook 全球主力组装生产基地与良品率把控",
        recencyWeight: 1.0,
      },
      {
        id: "GOOGL",
        name: "Alphabet 谷歌 (GOOGL)",
        type: "COMPETITOR",
        marketSymbol: "GOOGL",
        sector: "互联网与端侧系统",
        beta: 1.1,
        marketCap: "$2.1T",
        recentSignalScore: 0.65,
        description: "Android 阵营主力竞品，同时每年向苹果支付数十亿美元 Safari 默认搜索分成 (ISA)",
        recencyWeight: 1.0,
      },
      {
        id: "APPLE_INTELLIGENCE",
        name: "Apple Intelligence 端侧模型换机潮",
        type: "CONCEPT",
        sector: "端侧 AI 升级",
        beta: 1.15,
        recentSignalScore: 0.8,
        description: "驱动全球 10 亿存量 iPhone 用户进入超级换机周期 (Supercycle)",
        recencyWeight: 1.0,
      },
    ],
    edges: [
      {
        source: "TSM",
        target: "AAPL",
        relation: "3nm 产能独占保障新款 iPhone 芯片算力与能效领先",
        relationType: "UPSTREAM_SUPPLIER",
        exposurePct: 0.7,
        elasticity: 0.85,
        timeLagDays: 7,
        impact: "POSITIVE",
        recencyWeight: 1.0,
      },
      {
        source: "APPLE_INTELLIGENCE",
        target: "AAPL",
        relation: "端侧隐私 AI 体验拉动高端 Pro 机型销量占比提高与均价 (ASP) 提升",
        relationType: "CONCEPT_THEME",
        exposurePct: 0.55,
        elasticity: 1.1,
        timeLagDays: 4,
        impact: "POSITIVE",
        recencyWeight: 1.0,
      },
      {
        source: "GOOGL",
        target: "AAPL",
        relation: "司法部反垄断诉讼若判定分成违规，可能削减苹果高毛利服务业务现金流",
        relationType: "COMPETITOR",
        exposurePct: 0.15,
        elasticity: -0.45,
        timeLagDays: 10,
        impact: "NEGATIVE",
        recencyWeight: 1.0,
      },
    ],
  },

  MSFT: {
    symbol: "MSFT",
    companyName: "Microsoft Corporation (微软)",
    sector: "企业云基础设施、企业级 SaaS 与生成式 AI",
    marketCap: "$3.1T",
    beta: 1.15,
    rootDescription: "Azure 云计算、Copilot 生产力软件与 OpenAI 战略同盟",
    nodes: [
      {
        id: "MSFT",
        name: "微软 (MSFT)",
        type: "ROOT_STOCK",
        marketSymbol: "MSFT",
        sector: "企业云与软件",
        beta: 1.15,
        marketCap: "$3.1T",
        recentSignalScore: 0.75,
        description: "Azure 云增长稳健，M365 Copilot 商业化渗透提速",
        recencyWeight: 1.0,
      },
      {
        id: "NVDA",
        name: "英伟达 (NVDA)",
        type: "SUPPLIER",
        marketSymbol: "NVDA",
        sector: "算力芯片",
        beta: 1.65,
        recentSignalScore: 0.85,
        description: "提供 Azure AI 集群所需核心 GPU 与 InfiniBand 高速交换网络",
        recencyWeight: 1.0,
      },
      {
        id: "OPENAI",
        name: "OpenAI 独家战略结盟",
        type: "SUPPLIER",
        sector: "前沿大模型",
        beta: 1.4,
        recentSignalScore: 0.8,
        description: "GPT-4o/o1 核心模型技术授权独家入驻 Azure 云与 Office 生态",
        recencyWeight: 1.0,
      },
      {
        id: "AMZN",
        name: "亚马逊 AWS (AMZN)",
        type: "COMPETITOR",
        marketSymbol: "AMZN",
        sector: "公有云计算",
        beta: 1.25,
        marketCap: "$1.9T",
        recentSignalScore: 0.6,
        description: "全球公有云第一大份额直接竞品，加速自研 Trainium 芯片与 Bedrock 平台",
        recencyWeight: 1.0,
      },
      {
        id: "GOOGL",
        name: "谷歌 GCP (GOOGL)",
        type: "COMPETITOR",
        marketSymbol: "GOOGL",
        sector: "公有云与多模态 AI",
        beta: 1.1,
        marketCap: "$2.1T",
        recentSignalScore: 0.65,
        description: "Gemini 生态与 GCP 云服务在中大型企业客户中形成有力争夺",
        recencyWeight: 1.0,
      },
    ],
    edges: [
      {
        source: "OPENAI",
        target: "MSFT",
        relation: "模型代际领先驱动企业客户首选 Azure AI 云迁移",
        relationType: "UPSTREAM_SUPPLIER",
        exposurePct: 0.5,
        elasticity: 0.95,
        timeLagDays: 3,
        impact: "POSITIVE",
        recencyWeight: 1.0,
      },
      {
        source: "NVDA",
        target: "MSFT",
        relation: "算力供应链供给稳定性直接决定 Azure AI 收入增速上行空间",
        relationType: "UPSTREAM_SUPPLIER",
        exposurePct: 0.45,
        elasticity: 0.75,
        timeLagDays: 5,
        impact: "POSITIVE",
        recencyWeight: 1.0,
      },
      {
        source: "AMZN",
        target: "MSFT",
        relation: "公有云价格战与企业迁移折扣争夺存量大型 IT 预算",
        relationType: "COMPETITOR",
        exposurePct: 0.3,
        elasticity: -0.4,
        timeLagDays: 5,
        impact: "NEGATIVE",
        recencyWeight: 1.0,
      },
    ],
  },
};

/**
 * 针对未预置在静态库中的任意美股标的，依据行业类型和代码自动合成高仿真的产业链因果网络
 */
export function buildDynamicEcosystemForSymbol(
  symbol: string,
  companyName?: string,
  sector?: string
): StockEcosystemDefinition {
  const sym = symbol.toUpperCase();
  const cName = companyName || sym;
  const nowIso = new Date().toISOString();

  // 根据标的代码特征推测行业属性
  const isSemi = /^(AMD|INTC|AVGO|QCOM|MU|ARM|ASML|TSM|TXN|AMAT|LRCX|KLAC)$/i.test(sym);
  const isCloudOrSoftware = /^(CRM|NOW|SNOW|PLTR|ORCL|ADBE|WDAY|DDOG|PANW|CRWD)$/i.test(sym);
  const isConsumer = /^(KO|PEP|PG|NKE|MCD|COST|WMT|TGT|SBUX)$/i.test(sym);
  const isBio = /^(LLY|NVO|PFE|MRK|ABBV|AMGN|GILD|BIIB)$/i.test(sym);
  const isFinancial = /^(JPM|BAC|GS|MS|V|MA|AXP|C|WFC)$/i.test(sym);

  if (isSemi) {
    return {
      symbol: sym,
      companyName: cName,
      sector: "半导体与集成电路设计",
      marketCap: "$80B-$300B",
      beta: 1.45,
      rootDescription: `${cName} 核心半导体芯片研发与全球化交付`,
      nodes: [
        { id: sym, name: `${cName} (${sym})`, type: "ROOT_STOCK", marketSymbol: sym, sector: "半导体", beta: 1.45, recentSignalScore: 0.6, description: `${cName} 核心主营业务`, recencyWeight: 1.0, createdAt: nowIso },
        { id: "TSM", name: "台积电 (TSM)", type: "SUPPLIER", marketSymbol: "TSM", sector: "晶圆代工", beta: 1.2, recentSignalScore: 0.7, description: "先进制程与成熟制程核心代工制造保障", recencyWeight: 1.0, createdAt: nowIso },
        { id: "ASML", name: "阿斯麦 (ASML)", type: "SUPPLIER", marketSymbol: "ASML", sector: "光刻设备", beta: 1.3, recentSignalScore: 0.5, description: "光刻设备扩产交期影响全行业晶圆供应", recencyWeight: 1.0, createdAt: nowIso },
        { id: "GLOBAL_TECH_DEMAND", name: "全球云厂商与消费电子端侧需求", type: "CLIENT", sector: "下游市场", beta: 1.2, recentSignalScore: 0.65, description: "数据中心、PC与智能终端需求复苏采购周期", recencyWeight: 1.0, createdAt: nowIso },
        { id: "SEMI_INVENTORY_CYCLE", name: "全球半导体去库存与资本开支周期", type: "CONCEPT", sector: "行业周期", beta: 1.3, recentSignalScore: 0.6, description: "库存周转天数 (DOI) 与晶圆厂稼动率修复", recencyWeight: 1.0, createdAt: nowIso },
        { id: "FED_POLICY", name: "美联储利率与科技股流动性", type: "MACRO", sector: "宏观利率", beta: 0.9, recentSignalScore: 0.3, description: "高 Beta 成长板块估值贴现因子", recencyWeight: 1.0, createdAt: nowIso },
      ],
      edges: [
        { source: "TSM", target: sym, relation: "晶圆代工产能分配与报价调整直接影响毛利率", relationType: "UPSTREAM_SUPPLIER", exposurePct: 0.6, elasticity: 0.8, timeLagDays: 7, impact: "POSITIVE", recencyWeight: 1.0, createdAt: nowIso },
        { source: "GLOBAL_TECH_DEMAND", target: sym, relation: "下游终端订单采购放量驱动季度营收上修", relationType: "DOWNSTREAM_CLIENT", exposurePct: 0.7, elasticity: 0.9, timeLagDays: 5, impact: "POSITIVE", recencyWeight: 1.0, createdAt: nowIso },
        { source: "SEMI_INVENTORY_CYCLE", target: sym, relation: "行业周期触底反弹拉动产品均价与毛利扩张", relationType: "CONCEPT_THEME", exposurePct: 0.5, elasticity: 1.1, timeLagDays: 3, impact: "POSITIVE", recencyWeight: 1.0, createdAt: nowIso },
        { source: "FED_POLICY", target: sym, relation: "降息预期提振科技板块风险偏好与估值乘数", relationType: "MACRO_DRIVER", exposurePct: 0.3, elasticity: 0.6, timeLagDays: 1, impact: "POSITIVE", recencyWeight: 1.0, createdAt: nowIso },
      ],
    };
  }

  if (isCloudOrSoftware) {
    return {
      symbol: sym,
      companyName: cName,
      sector: "企业级 SaaS 与云计算软件",
      marketCap: "$40B-$200B",
      beta: 1.35,
      rootDescription: `${cName} 企业级云服务与数字化解决方案`,
      nodes: [
        { id: sym, name: `${cName} (${sym})`, type: "ROOT_STOCK", marketSymbol: sym, sector: "企业软件", beta: 1.35, recentSignalScore: 0.55, description: `${cName} 企业级软件订阅与云服务`, recencyWeight: 1.0, createdAt: nowIso },
        { id: "MSFT_AZURE_AWS", name: "公有云底层基建 (AWS/Azure)", type: "SUPPLIER", sector: "云计算基建", beta: 1.1, recentSignalScore: 0.7, description: "软件底层算力、存储与机房托管成本支撑", recencyWeight: 1.0, createdAt: nowIso },
        { id: "FORTUNE_500_IT_BUDGET", name: "全球 500 强企业 IT 数字化预算", type: "CLIENT", sector: "下游企业采购", beta: 1.2, recentSignalScore: 0.5, description: "企业客户净留存率 (NDR) 与席位扩张速度", recencyWeight: 1.0, createdAt: nowIso },
        { id: "GENAI_WORKFLOW", name: "生成式 AI 工作流深度整合", type: "CONCEPT", sector: "AI 应用赋能", beta: 1.4, recentSignalScore: 0.8, description: "通过 AI Agent 提升 ARPU 值与产品壁垒", recencyWeight: 1.0, createdAt: nowIso },
        { id: "FED_RATE", name: "美联储利率与 SaaS 估值倍数", type: "MACRO", sector: "宏观折现率", beta: 1.0, recentSignalScore: 0.3, description: "SaaS 行业 EV/ARR 估值乘数对无风险利率极度敏感", recencyWeight: 1.0, createdAt: nowIso },
      ],
      edges: [
        { source: "FORTUNE_500_IT_BUDGET", target: sym, relation: "大客户订阅留存与新增席位直接决定 ARR 增速", relationType: "DOWNSTREAM_CLIENT", exposurePct: 0.75, elasticity: 0.95, timeLagDays: 5, impact: "POSITIVE", recencyWeight: 1.0, createdAt: nowIso },
        { source: "GENAI_WORKFLOW", target: sym, relation: "AI 助理商业化落地提升产品提价能力", relationType: "CONCEPT_THEME", exposurePct: 0.45, elasticity: 1.2, timeLagDays: 3, impact: "POSITIVE", recencyWeight: 1.0, createdAt: nowIso },
        { source: "FED_RATE", target: sym, relation: "利率环境宽紧决定高估值软件股的溢价空间", relationType: "MACRO_DRIVER", exposurePct: 0.4, elasticity: 0.8, timeLagDays: 1, impact: "POSITIVE", recencyWeight: 1.0, createdAt: nowIso },
      ],
    };
  }

  // 默认行业通用产业链拓扑
  return {
    symbol: sym,
    companyName: cName,
    sector: sector || "全美股精选核心产业",
    marketCap: "$50B+",
    beta: 1.1,
    rootDescription: `${cName} 核心主业与行业上下游博弈`,
    nodes: [
      { id: sym, name: `${cName} (${sym})`, type: "ROOT_STOCK", marketSymbol: sym, sector: "核心标的", beta: 1.1, recentSignalScore: 0.5, description: `${cName} 核心主营业务`, recencyWeight: 1.0, createdAt: nowIso },
      { id: `${sym}_UPSTREAM`, name: `${sym} 关键上游原材料/核心供应商`, type: "SUPPLIER", sector: "供应链", beta: 0.95, recentSignalScore: 0.4, description: "主要原材料、关键零组件与外包服务成本端", recencyWeight: 1.0, createdAt: nowIso },
      { id: `${sym}_DOWNSTREAM`, name: `${sym} 核心客群与终端分销渠道`, type: "CLIENT", sector: "客户渠道", beta: 1.05, recentSignalScore: 0.55, description: "主要营收贡献大客户与渠道终端消费能力", recencyWeight: 1.0, createdAt: nowIso },
      { id: `${sym}_COMPETITOR`, name: `${sym} 同行业主力竞争对手`, type: "COMPETITOR", sector: "同业竞品", beta: 1.15, recentSignalScore: 0.1, description: "争夺市场份额与行业定价权的竞争者", recencyWeight: 1.0, createdAt: nowIso },
      { id: "MACRO_LIQUIDITY", name: "美联储利率环境与宏观流动性", type: "MACRO", sector: "宏观经济", beta: 0.85, recentSignalScore: 0.35, description: "宏观资本成本、汇率与大盘风险偏好", recencyWeight: 1.0, createdAt: nowIso },
      { id: "SECTOR_THEME", name: "行业景气度与盈利预期修正", type: "CONCEPT", sector: "行业主题", beta: 1.2, recentSignalScore: 0.6, description: "行业供需格局改善与一致预期上调", recencyWeight: 1.0, createdAt: nowIso },
    ],
    edges: [
      { source: `${sym}_UPSTREAM`, target: sym, relation: "上游成本波动直接传导至产品毛利率", relationType: "UPSTREAM_SUPPLIER", exposurePct: 0.4, elasticity: 0.6, timeLagDays: 7, impact: "POSITIVE", recencyWeight: 1.0, createdAt: nowIso },
      { source: `${sym}_DOWNSTREAM`, target: sym, relation: "下游大客户采购意愿决定营收增长确定性", relationType: "DOWNSTREAM_CLIENT", exposurePct: 0.65, elasticity: 0.85, timeLagDays: 5, impact: "POSITIVE", recencyWeight: 1.0, createdAt: nowIso },
      { source: `${sym}_COMPETITOR`, target: sym, relation: "竞品促销与替代策略对存量市场份额构成挤压", relationType: "COMPETITOR", exposurePct: 0.25, elasticity: -0.45, timeLagDays: 3, impact: "NEGATIVE", recencyWeight: 1.0, createdAt: nowIso },
      { source: "SECTOR_THEME", target: sym, relation: "行业景气度上行推动 PE 估值中枢与订单放量", relationType: "CONCEPT_THEME", exposurePct: 0.5, elasticity: 1.05, timeLagDays: 2, impact: "POSITIVE", recencyWeight: 1.0, createdAt: nowIso },
      { source: "MACRO_LIQUIDITY", target: sym, relation: "宏观流动性充裕提升机构配置权重", relationType: "MACRO_DRIVER", exposurePct: 0.35, elasticity: 0.65, timeLagDays: 1, impact: "POSITIVE", recencyWeight: 1.0, createdAt: nowIso },
    ],
  };
}
